version: '3.8'
name: JSP_Servlet_Library_Simple_Management_System

services:
  postgres:
    image: postgres:15
    container_name: PostgreSQL_Database_Container
    restart: always
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
    - ./docker/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  tomcat:
    build:
        context: ..
        dockerfile: Dockerfile
    container_name: Tomcat_Servlet_Web_Container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres_db
      DB_USER: postgres
      DB_PASSWORD: postgres

volumes:
  pgdata: